### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by dreynolds** [stilvoid/please#1]
Some install instructions might be nice ;) **PLEASE**

**Comment by stilvoid** [comment]
Yep, definitely. I'm working on documentation now I've got stuff more or less working :)

In short though, grab a [build](https://github.com/stilvoid/please/releases) and stick in somewhere in your path :D

**Comment by stilvoid** [comment]
Fixed this in [864a91b](https://github.com/stilvoid/please/commit/864a91be02cae6cbf14777d1a70091f47953f679) btw :)
